name: patient_app
description: Application mobile Flutter pour les patients
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  
  # HTTP
  http: ^1.1.2
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Date Time
  intl: ^0.19.0
  table_calendar: ^3.0.9
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
